### ISSUE TITLE
Je trouve ce bot pas drôle 

### ISSUE THREAD

**Issue by Ubunetu** [win8bugpas/winbotsite#1]
Bonmidi, 

Je pense qu'il faudrait trouvé plus de blague drôle.

Cordialement, moi

**Comment by win8bugpas** [comment]
C’est le but, il fait des blagues nulles c’est la raison de son existence

**Comment by Ubunetu** [comment]
> C’est le but, il fait des blagues nulles c’est la raison de son existence

D'accord merci

**Comment by win8bugpas** [comment]
> Bonmidi, 
> 
> 
> 
> Je pense qu'il faudrait trouvé plus de blague drôle.
> Même si celles qui sont déjà sont déjà hyper drôles
> 
> 
> 
> Cordialement, moi

Ptdr
